AWSTemplateFormatVersion: "2010-09-09"
Description: Stack for the aws serverless ci cd project.

Resources:


#   __  __ _                                    _               
#  |  \/  (_) ___ _ __ ___  ___  ___ _ ____   _(_) ___ ___  ___ 
#  | |\/| | |/ __| '__/ _ \/ __|/ _ \ '__\ \ / / |/ __/ _ \/ __|
#  | |  | | | (__| | | (_) \__ \  __/ |   \ V /| | (_|  __/\__ \
#  |_|  |_|_|\___|_|  \___/|___/\___|_|    \_/ |_|\___\___||___/
                                                              
                                                  
  MicroserviceADev:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: microservice-a-dev
      Description: microservice-a-dev
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: false
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0 #aws/codebuild/python:3.6.5 # More info on Images: https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html
        Type: LINUX_CONTAINER
      Artifacts:
        Type: NO_ARTIFACTS
      BadgeEnabled: true
      ServiceRole: !Ref CodeBuildServiceRole
      Source:
        BuildSpec: microservice-a/buildspec.yml
        GitCloneDepth: 1
        Location: https://github.com/mfolivas/aws-serverless-ci-cd.git
        ReportBuildStatus: true
        Type: GITHUB
      TimeoutInMinutes: 60
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: ^refs/heads/(develop|master)
              ExcludeMatchedPattern: true

  MicroserviceBDevProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: microservice-b-dev
      Description: microservice-b-dev
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: false
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0 #aws/codebuild/python:3.6.5 # More info on Images: https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html
        Type: LINUX_CONTAINER
      Artifacts:
        Type: NO_ARTIFACTS
      BadgeEnabled: true
      ServiceRole: !Ref CodeBuildServiceRole
      Source:
        BuildSpec: microservice-b/buildspec.yml
        GitCloneDepth: 1
        Location: https://github.com/mfolivas/aws-serverless-ci-cd.git
        ReportBuildStatus: true
        Type: GITHUB
      TimeoutInMinutes: 60
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: ^refs/heads/(develop|master)
              ExcludeMatchedPattern: true


#   ____                  _____            
#  |  _ \  _____   __    | ____|_ ____   __
#  | | | |/ _ \ \ / /____|  _| | '_ \ \ / /
#  | |_| |  __/\ V /_____| |___| | | \ V / 
#  |____/ \___| \_/      |_____|_| |_|\_/  
                                         

  MicroservicesProjectDev:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: microservices-project-dev
      Description: Deploys all microservices in the dev environment.
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: false
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0 #aws/codebuild/python:3.6.5 # More info on Images: https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: STAGE
            Type: PLAINTEXT
            Value: dev
      Artifacts:
        Type: NO_ARTIFACTS
      BadgeEnabled: true
      ServiceRole: !Ref CodeBuildServiceRole
      Source:
        BuildSpec: buildspec.yml
        GitCloneDepth: 1
        Location: https://github.com/mfolivas/aws-serverless-ci-cd.git
        ReportBuildStatus: true
        Type: GITHUB
      TimeoutInMinutes: 60
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: ^refs/heads/develop
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_CUSTOM_CACHE

#   ____                _       _____            
#  |  _ \ _ __ ___   __| |     | ____|_ ____   __
#  | |_) | '__/ _ \ / _` |_____|  _| | '_ \ \ / /
#  |  __/| | | (_) | (_| |_____| |___| | | \ V / 
#  |_|   |_|  \___/ \__,_|     |_____|_| |_|\_/  
                                               

  MicroservicesProjectProd:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: microservices-project-prod
      Description: Deploys microservices to the prod environment.
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: false
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0 #aws/codebuild/python:3.6.5 # More info on Images: https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: STAGE
            Type: PLAINTEXT
            Value: prod
      Artifacts:
        Type: NO_ARTIFACTS
      BadgeEnabled: true
      ServiceRole: !Ref CodeBuildServiceRole
      Source:
        BuildSpec: buildspec.yml
        GitCloneDepth: 1
        Location: https://github.com/mfolivas/aws-serverless-ci-cd.git
        ReportBuildStatus: true
        Type: GITHUB
      TimeoutInMinutes: 60
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: ^refs/heads/master
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_CUSTOM_CACHE
  
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: "*"
                Effect: Allow
                Action:
                  - apigateway:*
                  - cloudformation:*
                  - cloudwatch:*
                  - dynamodb:*
                  - events:*
                  - iam:*
                  - lambda:*
                  - logs:*
                  - s3:*
                  - sns:*
                  - sqs:*
                  - ssm:*
